version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: denchik24/kitty_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: denchik24/kitty_frontend 
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: denchik24/kitty_gateway 
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80